In [3]:
import numpy as np


In [15]:
a = np.array([[1,2,3],[2,3,4]])
a

array([[1, 2, 3],
       [2, 3, 4]])

In [17]:
a.shape

(2, 3)

In [21]:
a.reshape(3,2)

array([[1, 2],
       [3, 2],
       [3, 4]])

In [20]:
N = 4
def transpose(A,B): 
 
 for i in range(N): 
  for j in range(N): 
   B[i][j] = A[j][i] 
 
# driver code 
A = [ [1, 1, 1, 1], 
 [2, 2, 2, 2], 
 [3, 3, 3, 3], 
 [4, 4, 4, 4]] 
 
 
B = A[:][:] # To store result 
 
transpose(A, B) 
 
print("Result matrix is") 
for i in range(N): 
 for j in range(N): 
  print(B[i][j], " ", end='') 
 print() 

Result matrix is
1  2  3  4  
2  2  3  4  
3  3  3  4  
4  4  4  4  


In [24]:
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [25]:
x


array([0., 0., 0., 0., 0.])

In [30]:
x = np.arange(10,20,2)
print (x)

[10 12 14 16 18]
